[versions]
agp = "8.10.2"
kotlin = "2.0.20"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.12.0"
lifecycleRuntimeKtx = "2.7.0"
googleAiClient = "0.9.0"
cameraxVersion = "1.3.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
google-ai-client = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "googleAiClient" }
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraxVersion" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraxVersion" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraxVersion" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraxVersion" }
